export const BETS = [
    " has to do 2 push ups",
    " can be tickled next round",
    " can be pinched next round (not to violently)",
    " will cook next time (nonestackable)",
    " has to go touch grass",
    " tell one random truth",
    " has to play next round standing on one leg",
    " has to lift of the ground the closest player to him (that other player can try to run away)",
    " has to like the game in my repo (https://github.com/EmberDragons?tab=repositories)",
    " has to do something impressive on the spot",
    " has to search a new word online that he didn't know",
    " has to show his search history",
    " has to play with his feet",
    " has to run as fast as he can if he doesn't want to get tickled XD (go get him)",
    " has to go buy food for the next day",
    " has to go to bed before midnight (get some sleep)",
    " has to stop playing LOL or never start",
    " has to tell a truth about yesterday",
    " has to tell a truth about one of the person around",
    " has to get up without using his hands",
    " has to touch his feet with his hands",
    " has to clean the house tomorrow",
    " has to play next round while listening to hardstyle",
    " has to start playing wordle",
    " has to show his instagram explore page",
]